const express = require('express');
const router = express.Router();
const { signup } = require('../controllers/signUpController');
const { login } = require('../controllers/loginController');
const { googleLogin } = require('../controllers/googleController'); 
const { validateSignup, validateLogin } = require('../middlewares/validationMiddleware');
router.post('/signup', validateSignup, signup);
router.post('/login', validateLogin, login);
router.get('/google', googleLogin);
module.exports = router;